package cmpt276.termproject.model;

import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.view.View;

import java.util.ArrayList;
import java.util.List;

import cmpt276.termproject.R;

public class CardDrawer extends View {

    private float RADIUS = 300f;
    private Paint paint = new Paint();
    private Canvas canvas;

    private List<Integer> images_list;

    private CardManager cardManager;
    private List<Integer> draw_card_imgs;

    public CardDrawer (Context context, AttributeSet attrs){
        super(context, attrs);

        setup();

    }

    private void setup(){
        cardManager = CardManager.getInstance();
        draw_card_imgs = new ArrayList<>();

        initialiseImagesArray();

    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        this.canvas = canvas;

        drawCard((getWidth() / 2f)   , (getHeight() / 2f) - RADIUS );
    }


    private void initialiseImagesArray(){
        TypedArray typedArray = getResources().obtainTypedArray(R.array.theme_1_images);
        //Change theme if applicable
        if (cardManager.getTheme() == 2){
            typedArray = getResources().obtainTypedArray(R.array.theme_2_images);
        }

        images_list = new ArrayList<>();
        for (int i = 0; i < typedArray.length(); i ++){
            images_list.add(typedArray.getResourceId(i, R.drawable.circle));
        }
        //Recycle Typed array for garbage collection
        typedArray.recycle();

    }

    private void createDrawableArray(){
        int[] draw_card = cardManager.getDrawCard();

        //If card already exists, replace with new one
        if (draw_card_imgs.size() > 0) {
            draw_card_imgs = new ArrayList<>();
        }

        //Create a mapped array of drawable items
        if (draw_card[0] != -1) {
            for (int value : draw_card) {
                draw_card_imgs.add(images_list.get(value));
            }
        }
    }


    private void drawCard(float x , float y ){
        paint.setStyle(Paint.Style.FILL);
        paint.setStrokeWidth(10f);
        paint.setColor(Color.GRAY);

        //Generate the Drawables from the array of ints that was generated by the CardManager
        createDrawableArray();

        canvas.drawCircle(x,y,RADIUS ,paint);

        //Drawing images around the card evenly distributed
        int section_size = 360 / draw_card_imgs.size();

        for (int i = 0 ; i < draw_card_imgs.size() ; i ++) {
            float rad = (float) Math.toRadians(i* section_size);
            int width = (int) (Math.cos(rad) * RADIUS * (0.6f));
            int height = (int) (Math.sin(rad) * RADIUS * (0.6f));

            Bitmap card_img = BitmapFactory.decodeResource(getContext().getResources(), draw_card_imgs.get(i));
            Bitmap scaled_img = Bitmap.createScaledBitmap(card_img, 150, 150, true);

            canvas.drawBitmap(scaled_img,width + x - scaled_img.getWidth()/2f , height + y - scaled_img.getHeight()/2f, null);
        }

    }


}
